### ISSUE TITLE
Doesn't support for jsx files

### ISSUE THREAD

**Issue by jaroslawziolkowski** [tightenco/laravel-elixir-webpack-react#1]
I installed package and set into gulpfile.js

```
const elixir = require('laravel-elixir');
require('laravel-elixir-webpack-react');
elixir(mix => {
    mix.sass('app.scss')
    .webpack('react/components/app.jsx','./public/js/przyszlosc.js');
});
```

when I use

```
import PspDashboard from './dashboard';
```

can't find file but when I use

```
import PspDashboard from './dashboard.jsx ';
```

it works. exlxir try load no extension, js and json no jsx.

**Comment by nakie** [comment]
I ran into this same issue,  Created a pull request to update the webpack configuration so .JSX files are  resolved on imports.

**Comment by samanthamichele7** [comment]
I believe this should be fixed now 👍  Thanks for the PR, @nakie, and sorry about the delay on getting it merged in.
